<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29030" started-at="2018-11-05T15:51:24Z" finished-at="2018-11-05T15:51:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29030" started-at="2018-11-05T15:51:24Z" finished-at="2018-11-05T15:51:53Z">
      <class name="com.computerDB.read.Read001">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.computerDB.read.Read001@6d7b4f4c]" name="setUp" is-config="true" duration-ms="24030" started-at="2018-11-05T15:51:24Z" finished-at="2018-11-05T15:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[FireFox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="readPositiveTestCase()[pri:0, instance:com.computerDB.read.Read001@6d7b4f4c]" name="readPositiveTestCase" duration-ms="2619" started-at="2018-11-05T15:51:48Z" finished-at="2018-11-05T15:51:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Required Introduced date not found!! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Required Introduced date not found!! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.computerDB.read.Read001.readPositiveTestCase(Read001.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readPositiveTestCase -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:com.computerDB.read.Read001@6d7b4f4c]" name="tearDownTest" is-config="true" duration-ms="2313" started-at="2018-11-05T15:51:51Z" finished-at="2018-11-05T15:51:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
      </class> <!-- com.computerDB.read.Read001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
